# Generated by Django 4.2.3 on 2023-07-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='price',
            fields=[
                ('internet_id', models.AutoField(primary_key=True, serialize=False)),
                ('internet_title', models.CharField(blank=True, max_length=60, null=True)),
                ('internet_model', models.CharField(blank=True, max_length=60, null=True)),
                ('internet_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('download_speed', models.CharField(blank=True, max_length=60, null=True)),
                ('upload_speed', models.CharField(blank=True, max_length=60, null=True)),
                ('data_cap', models.CharField(blank=True, max_length=60, null=True)),
                ('contract', models.CharField(blank=True, max_length=60, null=True)),
                ('setup_cost', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
