# Generated by Django 4.2.3 on 2023-07-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internetApp', '0002_pricepopular'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricePopular',
        ),
        migrations.AlterField(
            model_name='price',
            name='setup_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
