# Generated by Django 4.2.3 on 2023-07-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internetApp', '0004_pricebusiness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_name', models.CharField(blank=True, max_length=60, null=True)),
                ('message_surname', models.CharField(blank=True, max_length=60, null=True)),
                ('message_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message_comment', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
