# Generated by Django 4.2.3 on 2023-07-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internetApp', '0009_price_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.RemoveField(
            model_name='price',
            name='slug',
        ),
    ]
