# Generated by Django 4.2.3 on 2023-07-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internetApp', '0010_posts_remove_price_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.AddField(
            model_name='price',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
