# Generated by Django 4.2.3 on 2023-07-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internetApp', '0011_delete_posts_price_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricebusiness',
            name='slug1',
            field=models.SlugField(default=''),
        ),
    ]
