# Generated by Django 4.2.3 on 2023-07-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internetApp', '0012_pricebusiness_slug1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricebusiness',
            old_name='slug1',
            new_name='slug',
        ),
    ]
