# Generated by Django 4.2.3 on 2023-07-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internetApp', '0013_rename_slug1_pricebusiness_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internet_title', models.CharField(blank=True, max_length=60, null=True)),
                ('internet_model', models.CharField(blank=True, max_length=60, null=True)),
                ('internet_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('download_speed', models.CharField(blank=True, max_length=60, null=True)),
                ('upload_speed', models.CharField(blank=True, max_length=60, null=True)),
                ('data_cap', models.CharField(blank=True, max_length=60, null=True)),
                ('contract', models.CharField(blank=True, max_length=60, null=True)),
                ('setup_cost', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='internet_product',
            field=models.ManyToManyField(to='internetApp.product'),
        ),
    ]
