# Generated by Django 4.2.3 on 2023-07-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internetApp', '0014_product_price_internet_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='internet_product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
