# Generated by Django 4.2.3 on 2023-07-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internetApp', '0018_rename_slug_reservation_paketa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='paketa',
            field=models.SlugField(default=False),
        ),
    ]
