# Generated by Django 4.2.3 on 2023-07-19 09:32

from django.db import migrations, models
import internetApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('internetApp', '0020_remove_reservation_paketa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_paket',
            field=models.ForeignKey(blank=True, null=True, on_delete=internetApp.models.PriceBusiness, to='internetApp.price'),
        ),
    ]
