# Generated by Django 4.2.3 on 2023-07-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internetApp', '0023_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
