# Generated by Django 4.2.3 on 2023-07-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internetApp', '0028_reservation_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='is_paid',
        ),
    ]
