# Generated by Django 4.2.3 on 2023-08-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internetApp', '0030_reservation_is_paid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
